### PR TITLE
Add linux dbg target, disallow wrong options, add help

### PR DESCRIPTION
**Pull request by capnm**
WIP: A scons file from my similar project modified for your project,
the windows and osx targets were not tested.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Looks pretty good. Cool to have some help output. 

One small question, why remove the use of elif? I personally find it clearer that there is only one path through the code but I noticed that a lot of people don't use elif.

**Comment by capnm** [comment]
For me it's only for fast copying / pasting between different files;)
Can you check if it works with VS 2017? I will then also change the comment.

**Comment by BastiaanOlij** [comment]
Compiles fine for me on Windows :) The -h options works like a charm too, just take out some of the obsolete settings.

**Comment by capnm** [comment]
> Compiles fine for me on Windows :) The -h options works like a charm too, just take out some of the obsolete settings.

Do you want to remove the 64bits and the Linux, p alias settings?

Does it work without the `env.Append(ENV = os.environ)` line? Should I leave it there?

**Comment by BastiaanOlij** [comment]
I don't really have an opinion on the -p setting. I can see some people would like to have short switches to minimize typing. I was more talking about the godot_headers, cpp_bindings_path and that type of setting because there really is no point in ever changing those now that they are submodules.

I'm conflicted about the 64bits setting, I'm really surprised there are still people compiling for 32bit architectures.

I'd leave the os.environ thing as is, I remember there was something between VC 2015 and VC 2017

**Comment by capnm** [comment]
Agree, the 32-bit architecture should finally die!
Ok, I just left the project-specific names there. 
I hope I didn't break anything. After the last thread-related changes by reduz, I'm surprised how everything runs relatively smoothly under Linux—without crashing every 10 minutes :-)

The next step would be eventually to call godot for the api update and
_godot-cpp's SConstruct_, …

**Comment by BastiaanOlij** [comment]
Nice to haves for sure but I think it's fine to keep godot-cpp and the bindings separate. The further along we get the more stable the API will be, the less likely the need to recompile godot-cpp. I think we'll eventually get to a point where you download header files and precompiled binaries for godot-cpp.

Are you still working on this or should I merge the changes in?

**Comment by capnm** [comment]
> Are you still working on this or should I merge the changes in?

Yes, if you don't have objections.

My own projects need external libraries, many different compiler options and so on. It gets complicated, so I use scons to do it all. It was just a theoretical suggestion of what you could do next. I think you've already noticed that English isn't my native language ;o)

**Comment by BastiaanOlij** [comment]
> My own projects need external libraries, many different compiler options and so on. It gets complicated, so I use scons to do it all. It was just a theoretical suggestion of what you could do next. I think you've already noticed that English isn't my native language ;o)

All good :) English is my second language too :)

**Pull request merged**
